### ISSUE TITLE
AppImage shows developer console

### ISSUE THREAD

**Issue by probonopd** [ReproNim/brainverse#151]
Seems to show developer stuff:

![](https://github.com/AppImage/appimage.github.io/raw/617a2718e07ee1694a570762519d9a31a70db8dc/database/BrainVerse/screenshot.png)

Reference:
https://github.com/AppImage/appimage.github.io/pull/368

**Comment by smpadhy** [comment]
same as #140 . It has been fixed and is in the master branch. It will be released in next version.

**Comment by probonopd** [comment]
Thanks, much better now!

![](https://raw.githubusercontent.com/AppImage/appimage.github.io/908def828bfa92e1feca0385f053f222560f764a/database/BrainVerse/screenshot.png)
