### ISSUE TITLE
Can't add item to experiment plan session

### ISSUE THREAD

**Issue by vkozloff** [ReproNim/brainverse#162]
I am unable to add an item to a session in an experiment plan
<img width="1415" alt="screen shot 2018-03-09 at 2 51 21 pm" src="https://user-images.githubusercontent.com/29068838/37226880-5c0c0bda-23a9-11e8-90f7-153d3e9b84a2.png">

**Comment by vkozloff** [comment]
I can click on "add item," but there is no option to edit it and the "add" button doesn't save it

**Comment by smpadhy** [comment]
@vkozloff This issue has been resolved. Please check if you are using recent version 0.0.3 of BrainVerse.
