### ISSUE TITLE
Unable to edit existing item in session

### ISSUE THREAD

**Issue by vkozloff** [ReproNim/brainverse#163]
I can't edit or save changes

<img width="1398" alt="screen shot 2018-03-09 at 2 53 51 pm" src="https://user-images.githubusercontent.com/29068838/37227018-c6ae90fc-23a9-11e8-9456-440172588963.png">

**Comment by smpadhy** [comment]
@vkozloff I can not reproduce this bug with the recent version 0.0.3 BrainVerse. Please make sure you are using the recent version of Brainverse.

**Comment by smpadhy** [comment]
Based on our last discussion, this is resolved.
