### ISSUE TITLE
Feature request: Change Item Names in Experiment Planner

### ISSUE THREAD

**Issue by vkozloff** [ReproNim/brainverse#164]
It would be great to be able to edit the name of an item within a session, not just the description

**Comment by smpadhy** [comment]
@vkozloff This feature already exists. Click on the edit icon of description. It displays edit form. You can type new task name to change the name of the item and save.

**Comment by smpadhy** [comment]
@vkozloff let me know if you are able to change the item name.

**Comment by smpadhy** [comment]
Based on our last discussion, this is resolved.

**Comment by vkozloff** [comment]
Thanks!
