### ISSUE TITLE
Cannot save in data acquisition mode

### ISSUE THREAD

**Issue by vkozloff** [ReproNim/brainverse#221]
We open a form in data acquisition mode
<img width="2310" alt="screen shot 2018-07-16 at 2 10 57 pm" src="https://user-images.githubusercontent.com/29068838/42775346-20701df0-8902-11e8-9bfb-4812444d4fed.png">
Selecting save highlights the button but doesn't change the screen
<img width="510" alt="screen shot 2018-07-16 at 2 10 51 pm" src="https://user-images.githubusercontent.com/29068838/42775353-226c4b06-8902-11e8-8cf9-6e20b3dab3b5.png">

**Comment by sanuann** [comment]
resolved in release v0.0.8-alpha
