### ISSUE TITLE
Cannot edit instruments

### ISSUE THREAD

**Issue by vkozloff** [ReproNim/brainverse#224]
We are not able to use the instrument editor, which appears blank. Pointing the cursor at the editor gives a spinning pinwheel.

<img width="1257" alt="screen shot 2018-07-19 at 7 08 58 pm" src="https://user-images.githubusercontent.com/29068838/42974887-4a4f38fe-8b87-11e8-82f3-c1cb50b75475.png">

**Comment by vkozloff** [comment]
Selecting the add button in a session of an experiment planner also creates a spinning pinwheel

**Comment by vkozloff** [comment]
This happened after trying to edit an instrument which appeared blank in the instruments list.

**Comment by vkozloff** [comment]
workaround by deleting instruments from termforms folder

**Comment by sanuann** [comment]
resolved in release v0.0.8-alpha
