### ISSUE TITLE
Instruments cannot be edited

### ISSUE THREAD

**Issue by Qlab-UDel** [ReproNim/brainverse#238]
We add a field to the instrument

<img width="663" alt="screen shot 2018-08-13 at 5 20 06 pm" src="https://user-images.githubusercontent.com/30700680/44058774-4c2b989e-9f1d-11e8-8b53-500aca73eabc.png">

However, after we save locally and push to GitHub, the changes are not reflected. Instead, the instrument content appears as the default

<img width="683" alt="screen shot 2018-08-13 at 5 20 15 pm" src="https://user-images.githubusercontent.com/30700680/44058792-5d43bc10-9f1d-11e8-8ab0-bf359d5d6778.png">

**Comment by sanuann** [comment]
have u checked in the uploads/terms folder if the change is reflected there? Please let me know, in which case I just need to add it to the UI.

**Comment by sanuann** [comment]
I just checked. The current version creates a different instrument in the 'termforms' directory when new fields are added to it. And the updated instrument renders correctly in the instrument Editor for me.

**Comment by sanuann** [comment]
@Qlab-UDel is this error still there? If yes, please reopen or let me know.
